### ISSUE TITLE
Gatttool unable to connect with a Crownstone

### ISSUE THREAD

**Issue by Kvanr23** [Kvanr23/InternshipBluetoothLE#1]
I did the following commands to get the connection refused error:

- `sudo hcitool lescan`, to find the MAC address of the Crownstone

- `sudo gatttool -b <MAC ADDRESS> -I`, to start an interactive session with the MAC address.

- In the interactive gatttool interface, I entered `connect`, to try and connect with the Crownstone.

After around 40 seconds, gatttool responds with:
`Error: connect error: Connection refused (111)`

Searched on Google for some help and found this page from on Crownstone.rocks:
https://crownstone.rocks/2014/07/23/linux-and-ble
I used the command: `sudo hcitool -i hci0 lecc --random <MAC ADDRESS>`, but this returned a similar error:
`Could not create connection: Input/output error`

I assumed this is because the firmware changed a lot since 2014, but with the command `bluetoothctl`, I can connect with the Crownstone, and as I was told, it disconnects itself after 10 seconds (when nothing is sent).

So my next steps are finding out why bluetoothctl does work and gatttool does not.

**Comment by mrquincle** [comment]
```
gatttool -i hci0 -b E0:43:E9:89:12:61 --interactive -t random
[E0:43:E9:89:12:61][LE]> connect
Attempting to connect to E0:43:E9:89:12:61
Connection successful
[E0:43:E9:89:12:61][LE]>
```
I need more info, because this just does work on my system.

```
dpkg -S $(which gatttool)
bluez: /usr/bin/gatttool
```

```
apt show bluez
Package: bluez
Version: 5.53-0ubuntu3
Priority: optional
Section: admin
Origin: Ubuntu
Maintainer: Ubuntu Bluetooth team <ubuntu-bluetooth@lists.ubuntu.com>
Original-Maintainer: Debian Bluetooth Maintainers <pkg-bluetooth-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 4,910 kB
Depends: libc6 (>= 2.17), libdbus-1-3 (>= 1.9.14), libglib2.0-0 (>= 2.31.8), libreadline8 (>= 6.0), libudev1 (>= 196), kmod, udev (>= 170-1), lsb-base, dbus
Conflicts: bluez-alsa, bluez-audio (<= 3.36-3), bluez-utils (<= 3.36-3)
Breaks: udev (<< 170-1)
Replaces: bluez-alsa, bluez-audio (<= 3.36-3), bluez-input, bluez-network, bluez-serial, bluez-utils (<= 3.36-3), udev (<< 170-1)
Homepage: http://www.bluez.org
Task: ubuntu-desktop-minimal, ubuntu-desktop, kubuntu-desktop, xubuntu-core, xubuntu-desktop, lubuntu-desktop, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-budgie-desktop
Download-Size: 981 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
Description: Bluetooth tools and daemons
 This package contains tools and system daemons for using Bluetooth devices.
 .
 BlueZ is the official Linux Bluetooth protocol stack. It is an Open Source
 project distributed under GNU General Public License (GPL).
```

Why don't you also specify the hci interface with the gatt tool? Also make sure you use the `--random` option for the tool. 

If things do not work, start debugging. Make sure you are connecting with the right MAC address and you're in range and not already connected.

**Comment by mrquincle** [comment]
I also don't think you need `sudo` for using bluetooth on a modern OS. If it's not clear, start delving into `strace`, etc. to figure out what's going on.
